### ISSUE TITLE
Feature Request?!

### ISSUE THREAD

**Issue by MonoAdrian23** [pmmp/AntiInstaBreak#34] opened 2020-09-14 10:03 UTC
Can you add enable/disable world Support Please?
Because it doesnt work with any Playerhead Plugin.
In Config can add the Name of a World this Plugin Not Work.
Thank you very much!

**Comment by dktapps** [comment] 2020-09-14 10:11
I don't see why this is necessary.

**Comment by MonoAdrian23** [comment] 2020-09-14 11:31
The aim is to prevent you from getting an error when you click on a head. So many citybuild servers use heads exclusively in the citybuild world. If you can deactivate this in the plugin, heads can be used. A city build world can also be monitored by the team.

**Comment by Thunder33345** [comment] 2020-09-14 11:40
that's a problem with the plugin problem
we shouldn't need bent our back just to accommodate a plugin
instead please ask the plugin author to make it work/disabled on perworld basis
due to how the api has been setup, it would be easier for the plugin to just have a ignored worlds anyways

**Comment by dktapps** [comment] 2020-09-14 11:53
This sounds like treating the symptoms instead of the cause. Get the broken plugin fixed instead.

**Closed as completed by dktapps** 2020-09-14 11:53 UTC
Labels: enhancement
